### ISSUE TITLE
[bug] Redirect after save on the Edit Symptom page in monolithic-layered app

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#10]
### Steps

```sh
cd .\monolithic\monolithic-layered\
mvn spring-boot:run
```

Navigate to http://localhost:8080/symptoms/1

Click "Save"

### Demo

https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/5a54c364-4716-4110-8307-cb8b5b6f7a48

### Expected Result

Do not show "redirect:/symptoms" text to user. Show the [Symptoms](http://localhost:8080/symptoms) Page.

**Comment by naXa777** [comment]
Hint: only the Edit Symptom page is affected by #10. So take a look at how it works in [Edit Disease](http://localhost:8080/diseases/2) page or [Edit Pharmacy](http://localhost:8080/pharmacies/1) page, and find a difference which causes the bug.

**Comment by youngInnovator** [comment]
Kindly assign this bug to me.

**Comment by aabarmin** [comment]
Sure @youngInnovator, please go ahead with it!

**Comment by youngInnovator** [comment]
Implemented in #18

**Comment by aabarmin** [comment]
Thank you @youngInnovator, will have a look at your PR shortly.
