### ISSUE TITLE
[help needed] how to access GraphiQL in microservice-graphql app?

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#22]
I'd like to use GraphiQL for testing the microservice-graphql manually. I see it's listed in the dependencies:

```xml
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
        </dependency>
```

But I don't know how to find it. Is it even exposed?

![image](https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/546dfc0e-49bf-4129-91d4-4b6d7432c87a)

I've tried to enable this feature in application.yml as documented [here](https://docs.spring.io/spring-boot/docs/3.1.3/reference/html/web.html#web.graphql.graphiql), but I don't see any effect. Please help!

```yml
spring:
  graphql:
    graphiql:
      enabled: true
```

**Comment by aabarmin** [comment]
Hi @naXa777 

It seems, after migration of all the services to Spring Boot 3 GraphiQL stopped to work. Let me fix it in a mean while.
