### ISSUE TITLE
Increase Test Coverage for microservices apps

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#26]
Need to add automated tests to prevent errors like #19 from happening in future. It would be nice to have at least one test per Spring Boot app.

> The first thing you can do is write a simple sanity check test that will fail if the application context cannot start.

See https://spring.io/guides/gs/testing-web/ for example.

**Comment by naXa777** [comment]
@aabarmin please assign this issue to me

**Comment by aabarmin** [comment]
Sure @naXa777, please go ahead with the ticket.
