### ISSUE TITLE
Design a nice "404 Not Found" page for monolithic-layered app

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#28]
Run `MonolithicApplication` and visit http://localhost:8080/drugs/404 (non-existent drug ID).

### Actual Demo

![image](https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/ff6266fc-a2ee-4a1b-89c1-a99eabab5b5b)

### Expected Demo

![image](https://www.baeldung.com/wp-content/uploads/2018/04/error404.png)

(or something like this)

### Guide

1. Return 404 status code instead of 500
2. Read https://www.baeldung.com/spring-boot-custom-error-page
3. Design 404.html page
4. Apply 404 page to all resources: Drugs, Pharmacies, Diseases, etc.

**Comment by youngInnovator** [comment]
Kindly assign this to me

**Comment by youngInnovator** [comment]
Addressed in #50
