### ISSUE TITLE
Design a nice "500 Internal Server Error" page for monolithic-layered app

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#29]
Run MonolithicApplication and visit some page that generates server-side error.

### Actual Demo

![image](https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/ff6266fc-a2ee-4a1b-89c1-a99eabab5b5b)

### Expected Demo

![image](https://www.baeldung.com/wp-content/uploads/2018/04/error1.png)

(or something like this)

### Guide

1. Read https://www.baeldung.com/spring-boot-custom-error-page
2. Design 500.html page
3. Apply the 500 page to all resources: Drugs, Pharmacies, Diseases, etc.

**Comment by youngInnovator** [comment]
Kindly assign this to me

**Comment by youngInnovator** [comment]
Addressed in #51 Branch is based on #50. So Kindly first merge #50
