### ISSUE TITLE
Get rid of property injection, use constructor injection if possible 

### ISSUE THREAD

**Issue by aabarmin** [aabarmin/epam-microservices-training-2022#4]
Get rid of property injection, use constructor injection if possible

**Comment by naXa777** [comment]
this one looks easy. @aabarmin, can you assign to me please?

**Comment by aabarmin** [comment]
Thank you @naXa777 for helping with the issue. Please let me know if you need any assistance

**Comment by naXa777** [comment]
Done. @aabarmin please review #15
