### ISSUE TITLE
[bug] Broken routing in monolithic-layered app

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#7]
steps:
```sh
cd .\monolithic\monolithic-layered\
mvn spring-boot:run
```

Demo 

https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/7e4e3989-e153-4468-a234-a4824dfcde40

**Comment by naXa777** [comment]
broken link from Delivery Page to Edit Delivery Page

https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/c5816258-4aab-4c50-b5d1-cb9229a9df30

this bug looks similar, so I didn't create a new ticket. anyone who will work on this, please fix all such problems in monolithic-layered app in the scope of #7.

**Comment by Bogdan-Florian** [comment]
Hello, you can assign this to me. Thanks

**Comment by aabarmin** [comment]
Hi @Bogdan-Florian, please go ahead with this issue.

**Comment by aabarmin** [comment]
Fixed in #36
