### ISSUE TITLE
[bug] ${pageTitle} placeholder in title in monolithic-layered app

### ISSUE THREAD

**Issue by naXa777** [aabarmin/epam-microservices-training-2022#8]
steps:
```sh
cd .\monolithic\monolithic-layered\
mvn spring-boot:run
```

Demo 
![image](https://github.com/aabarmin/epam-microservices-training-2022/assets/3858548/dee81e44-9797-4b6f-8c1c-0c77595fbc51)

**Comment by naXa777** [comment]
@aabarmin hello! please assign this ticket to me.

**Comment by aabarmin** [comment]
Hi @naXa777, 

Sure, thank you for contributing.
